name: Generate Snake Animation

on:
  schedule: # roda uma vez por dia
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: BeatrizProjetos
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: actions/upload-artifact@v2
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg
